=== CostaTRAN/Portfolio/fr/content.dtd
<!ELEMENT content (title,homepage,cv,about,about_content,video,copyright)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ELEMENT cv (#PCDATA)>
<!ELEMENT about (#PCDATA)>
<!ELEMENT about_content (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href NMTOKEN #REQUIRED>
<!ELEMENT video (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>

=== CostaTRAN/Portfolio/fr/content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE content SYSTEM "content.dtd">
<content>
    <title>Portfolio de Costa TRAN</title>
    <homepage>Accueil</homepage>
    <cv>CV</cv>
    <about>À propos de moi</about>
    <about_content>
        Étudiant à l'école d'ingénieur Sup Galilée dans la spécialité informatique en apprentissage et apprenti ingénieur logiciel chez Forvia.
    </about_content>
    <video>Vidéo de présentation</video>
    <copyright>&#169; 2024 Costa TRAN. Tous droits réservés.</copyright>
</content>
